### ISSUE TITLE
Maybe an error?

### ISSUE THREAD

**Issue by lgqfhwy** [Hugstar/Solutions-Stanford-cs131-Computer-Vision-Foundations-and-Application#1]
Hello, I am a beginner, So if I was wrong, please forgive me.
In the hw1 1.3 Implementation, you implemented the conversion_nested, and accord the problem, we should get the similar result to the photo which problem provided.
Yes, I get the same photo(I made this implementation same to you), and you also get the same photo to the photo which problem provided.
<img width="478" alt="screen shot 2018-04-01 at 22 48 23" src="https://user-images.githubusercontent.com/16728136/38174377-15cfb654-35ff-11e8-9844-8ffb334281c6.png">
But if we see the matrix the photo represented, it is not same.
<img width="903" alt="screen shot 2018-04-01 at 22 50 10" src="https://user-images.githubusercontent.com/16728136/38174389-2c20e8f6-35ff-11e8-8cce-e11376b529c2.png">
We have the same results, we both are different to the photo which problem provided.
So I want to know it is problem was wrong, maybe the teacher provided a wrong photo?
or we both wrong.

To print the matrix, I add some code to the end of the code which problem provided.
<img width="588" alt="screen shot 2018-04-01 at 22 53 12" src="https://user-images.githubusercontent.com/16728136/38174445-a5d8f24c-35ff-11e8-8afd-8985ba7ae608.png">
I am very confused with this problem, please help me. Thank you so much.

**Comment by Hugstar** [comment]
Hi @lgqfhwy. Thanks for your comment!
the problem is with their answer, "What you should get".
You can verify it by using a library that provides a convolution function such as "scipy".

you can add the following code to the notebook cell and see that the result using conv_nested and the convolution from scipy produces the same result! 
Please let me know if it doesn't make sense to you. 
 
```
from scipy import ndimage
conv_nested_result = conv_nested(img, kernel)
scipy_conv_result = scipy.ndimage.convolve(img, kernel)

# Compare between conv_nested result and scipy convolution result on the image:
a = conv_nested_result
b = scipy_conv_result

print('Difference is {}'.format(np.sum(np.abs(a.flatten() - b.flatten())) / np.sum(np.abs(b.flatten()))*100))
```

**Comment by lgqfhwy** [comment]
Yes, I know. Thank you so much!
