### ISSUE TITLE
hw2 non_maximum_suppression and link_edges

### ISSUE THREAD

**Issue by jerett** [Hugstar/Solutions-Stanford-cs131-Computer-Vision-Foundations-and-Application#3]
in  non_maximum_suppression, I see you skip the gradient at the margin. I think it may need to caculate the gradient at the margin just like the official code of get_neighbors?
Also, for the link_edges function, why you only tranverse upper region? and I think here needs a BFS search.
Here is my [repo]((https://github.com/jerett/CS131_CompterVersion/blob/master/hw2_release/hw2.ipynb)) , you can have a look and compare my answer if you have time,  and we can discuss more. I want to figure out the answer.

**Comment by Hugstar** [comment]
Hi @jerett, Thanks for the comments.
1. Could you please try to explain what you mean when you refer to "the gradient at the margin"?
2. Yes, thanks for pointing that out! this is clearly a mistake. fixing it right now.

**Comment by Hugstar** [comment]
@jerett I've fixed number 2. Let me know if you still think changes in the function are necessary.

**Comment by jerett** [comment]
Hi, @Hugstar 
your code in non_maximum_suppression  only loop in range (1, H-1), (1, W-1), which I think may loop in (0, H), (0 W)? The gradient at (0, -1) out of bounds should be value 0?
```
H, W = G.shape
    out = np.zeros((H, W))

    # Round the gradient direction to the nearest 45 degrees
    theta = np.floor((theta + 22.5) / 45) * 45

    ### BEGIN YOUR CODE
    theta = theta%360
    for i in range(1, H-1):
        for j in range(1,W-1): 
```
In my code,  I pad G with (1, 1) width edge, just like code in conv solution.
```
    pad_width = ((1, 1), (1, 1))
    padded_G = np.pad(G, pad_width=pad_width, mode='constant', constant_values=0)

    for i in range(1, 1 + H):
        for j in range(1, 1 + W):
            g = padded_G[i][j]
            angle = theta[i - 1][j - 1]
            # angle = theta[i][j]
            g_next = padded_G[next(i, j, angle % 360)]
            g_before = padded_G[next(i, j, (angle + 180) % 360)]
            if g >= g_next and g >= g_before:
                out[i - 1][j - 1] = g
```

**Comment by Hugstar** [comment]
well, how to handle edges is always a question with these techniques. I personally don't feel like that's significant and impactful enough in order to have a special case for them, so i guess you can do it either with or without padding.
