### ISSUE TITLE
hw2_release edge.py

### ISSUE THREAD

**Issue by AaronLu47** [Hugstar/Solutions-Stanford-cs131-Computer-Vision-Foundations-and-Application#5]
hello, 
I am a little confused about the function link_edges in edge.py. The weak edges are included only if they are connected with strong edges, so is this equation ‘adjacent_edges = edges[x, y] or adjacent_edge’ right? Should it be 'adjacent_edges = strong_edges[x, y] or adjacent_edge'? The edges[] in the loop is changeable, and some of them are initially weak edges. Is the edge not directly connected with the strong edge but only connected with weak edge, which is connected with strong edge, also seen as the true edge in image?

**Comment by Hugstar** [comment]
Hi!
Please note that the definition is: weak edges are included if (and only if!) the weak edge is connected to an edge which is:
1. Strong edge
2. Weak edge that is connected in some path of weak edges to a strong edges

So if understand your question correctly - yes. If an edge A is connected with a weak edge B which is connected with a strong edge C, then A, B and C will all be strong edges.
 
![image](https://user-images.githubusercontent.com/13304579/39894454-9584a0d4-54af-11e8-8d25-d4c32a4d13fb.png)

Let me know if there's anything which could be more clear.

**Comment by AaronLu47** [comment]
wow! Thank u very much for your reply. Now I am much more clear about the definition!
