### ISSUE TITLE
Question on canny edges

### ISSUE THREAD

**Issue by oliverzzm** [Hugstar/Solutions-Stanford-cs131-Computer-Vision-Foundations-and-Application#8]
Did you get a final result of canny edges that looks like the picture embedded in the notebook?If you did, tell me what parameters you use, cause I was having a really hard time picking them to produce an output as close as that picture.

**Comment by Hugstar** [comment]
Hey! 
Yes, I did!
All the images embedded in the notebook were generated from the corresponding .py files: edge.py etc'.

If you could focus me on the specific function I'd be happy to help.

**Comment by oliverzzm** [comment]
Two questions:
1. In edge.py function non_maximum_suppression: why is 
`if current_angle == 0 or current_angle == 180:
                neighbors = [G[i, j-1], G[i, j+1]]
            elif current_angle == 45 or current_angle == 225:
                neighbors = [G[i-1, j-1], G[i+1, j+1]]
            elif current_angle == 90 or current_angle == 270:
                neighbors = [G[i-1, j], G[i+1, j]]
            elif current_angle == 135 or current_angle == 315:
                neighbors = [G[i-1, j+1], G[i+1, j-1]]`
I understand the horizontal and vertical case,but my code is the opposite of you dealing the 45 and 135 degreee case. Mine was  [G[i-1,j+1],G[i+1,j-1]] when angle = 45 and [G[i-1,j-1],G[i+1,j+1]] when angle = 135

2. I saw that you use two groups of parameters {[kernel_size:5,sigma:1.4],[kernel_size:3,sigma:1.2]} and the edge pictures generated by them are good, but still they are not as good-looking as the iguana_edges.png that is enclosed within the notebook released by the stanford vision group.  For examples, those triangles in the down-right corner are not closed in your output, but those are closed in the iguana_edges.png. Do you think it is possible to get that perfect result? If you do,what are those parameters?

**Comment by oliverzzm** [comment]
I understand the first question.Because the coordinate axes are different.  x is toward right, y is towards down.  And the 45 degree is actually pointing to the bottom-right corner.

**Comment by Hugstar** [comment]
Are you sure there's a difference?
This is their iguana_edges.png image:
![image](https://user-images.githubusercontent.com/13304579/47834655-04877d80-dda9-11e8-82a7-531fbe02281a.png)

This is my final result (in the notebook, where u can see the code):

![image](https://user-images.githubusercontent.com/13304579/47834686-1c5f0180-dda9-11e8-9cb9-d142624689f9.png)


Anyways, if there is a difference it just comes to different hyperparameters which can be searched for, but i have no clue which ones they used :)

**Comment by oliverzzm** [comment]
Got it,thanks for help!
